version: "3.9"

# TODO: move out env args
services:
  postgresql:
    image: "postgres"
    container_name: "pollos-demo-postgresql"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - /data\:/var/lib/postgresql/data
    networks:
      - backend
  games-server:
    image: "demo-server"
    container_name: "pollos-demo-server"
    ports:
      - "8000:8000"
    networks:
      - backend
  games-client:
    image: "demo-client"
    container_name: "pollos-demo-client"
    ports:
      - "3000:443"
    networks:
      - frontend

  nginx:
    image: nginx:latest
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - games-client
    ports:
      - "80:4000"
      - "443:4001"
    networks:
      - backend
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge