"""initial tables

Revision ID: 03c24ed83e9b
Revises: 
Create Date: 2022-07-24 08:44:04.816104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c24ed83e9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('tree_picture', sa.LargeBinary(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('core_radius', sa.Integer(), nullable=True),
    sa.Column('creation_year', sa.Integer(), nullable=True),
    sa.Column('plant_type', sa.String(), nullable=True),
    sa.Column('should_be_cut', sa.Boolean(), nullable=True),
    sa.Column('should_be_processed', sa.Boolean(), nullable=True),
    sa.Column('should_be_removed', sa.Boolean(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_id'), 'tree', ['id'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tree_id'], ['tree.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_tree_id'), table_name='tree')
    op.drop_table('tree')
    op.drop_table('user')
    # ### end Alembic commands ###
