"""New Migration 2testq

Revision ID: 0a53fdbf0a52
Revises: 557ca45ada40
Create Date: 2022-06-14 06:07:45.704243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a53fdbf0a52'
down_revision = '557ca45ada40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
