"""New Migration 2

Revision ID: 557ca45ada40
Revises: ece932f7c0f4
Create Date: 2022-06-14 05:30:21.568547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557ca45ada40'
down_revision = 'ece932f7c0f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
