"""initial tables

Revision ID: 71176ce046c1
Revises: 
Create Date: 2022-07-23 20:54:33.300355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71176ce046c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('tree_picture', sa.LargeBinary(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('core_radius', sa.Integer(), nullable=True),
    sa.Column('creation_year', sa.Integer(), nullable=True),
    sa.Column('plant_type', sa.String(), nullable=True),
    sa.Column('should_be_cut', sa.Boolean(), nullable=True),
    sa.Column('should_be_processed', sa.Boolean(), nullable=True),
    sa.Column('should_be_removed', sa.Boolean(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_id'), 'tree', ['id'], unique=False)
    op.drop_index('ix_post_id', table_name='post')
    op.drop_table('post')
    op.add_column('likes', sa.Column('tree_id', sa.Integer(), nullable=True))
    op.drop_constraint('likes_post_id_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'tree', ['tree_id'], ['id'])
    op.drop_column('likes', 'post_id')
    op.add_column('user', sa.Column('nickname', sa.String(), nullable=False))
    op.add_column('user', sa.Column('role', sa.Integer(), nullable=False))
    op.drop_column('user', 'name')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'age')
    op.drop_column('user', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'role')
    op.drop_column('user', 'nickname')
    op.add_column('likes', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_post_id_fkey', 'likes', 'post', ['post_id'], ['id'])
    op.drop_column('likes', 'tree_id')
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('header', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='post_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_pkey')
    )
    op.create_index('ix_post_id', 'post', ['id'], unique=False)
    op.drop_index(op.f('ix_tree_id'), table_name='tree')
    op.drop_table('tree')
    # ### end Alembic commands ###
