"""New Migration x

Revision ID: 85f501607920
Revises: 0a53fdbf0a52
Create Date: 2022-06-14 06:09:08.748384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f501607920'
down_revision = '0a53fdbf0a52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
