"""New Migration 1

Revision ID: ece932f7c0f4
Revises: 5f96286b2c6c
Create Date: 2022-06-14 05:29:29.292296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece932f7c0f4'
down_revision = '5f96286b2c6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
